ezequielzaquiere/hackatonPFB41rt

server/app.js
server/package-lock.json
server/package.json
server/src/middlewares/isUserAuthMiddleware.js.js
server/src/utils/generateErrorUtil.js

feat: middleware comprobacion si user esta logueado
feat: funcion generadora de errores
feat: middleware lectura body en formato json

feat:middleware comprobacion si user esta logueado

---

server/app.js
server/src/db/initDb.js

creacion estructura initDb

---

server/src/controllers/users/changePasswordController.js
server/src/models/users/changePasswordModel.js

a esperas del endpoint login usuario para seguir testeando

fix: changePassword (Controller + Model)

---

server/src/controllers/users/sendRecoveryPassEmailController.js

testeo del login y corrección de las importaciones en el archivo sendRecoveryPassEmailController

funcion login en funcionamiento

---

server/app.js
server/src/controllers/hackathones/index.js
server/src/controllers/registrations/index.js
server/src/controllers/registrations/registerHackathonController.js
server/src/middlewares/hackathonRegistrationStatusMiddleware.js
server/src/middlewares/index.js
server/src/models/registrations/insertRegistrationModel.js
server/src/models/registrations/selectRegistrationByUserIdAndHackathonId.js
server/src/models/users/selectUserByIdModel.js
server/src/routes/registrationRoutes.js
server/src/utils/sendEmailUtil.js
server/src/utils/validateDatesUtil.js

1. Va todo menos el correo, y creo que no es cosa nuestra

feact:registerHackathonController

---

server/README.md
server/src/controllers/hackathones/index.js
server/src/controllers/hackathones/ratingHackathonController.js
server/src/db/initDb.js
server/src/models/hackathones/insertRatingModel.js
server/src/models/hackathones/selectHackathonDetailsByIdModel.js
server/src/models/users/checkUserParticipationModel.js
server/src/models/users/insertUserModel.js
server/src/routes/hackathonRoutes.js

Se agrega elendpoint de valorar un hackathon del 1 al 5 después de la fecha de realización.

funcion rating hackathon

---

server/src/controllers/registrations/index.js
server/src/controllers/registrations/listHackathonParticipantsController.js
server/src/controllers/registrations/listUserRegistrationsController.js
server/src/models/registrations/listHackathonParticipantsModel.js
server/src/models/registrations/listUserRegistrationsModel.js
server/src/routes/registrationRoutes.js

- Added endpoint to get the hackathons a user has signed up for
- Added endpoint to get the list of users who have signed up for a given hackathon (subject to future change)

Added endpoints for seeing users in a given hackathon and hackathons a user is registered in

---

server/src/controllers/hackathones/hackathonDetailController.js
server/src/models/hackathones/selectHackathonDetailsByIdModel.js

- Added total number of registered users on a hackathon to the endpoint that retrieves its details.
- Corrected its import file on the controller

Added total number of registered users to hackathon details

---

server/src/controllers/hackathones/index.js
server/src/controllers/hackathones/listNextHackathonesController.js
server/src/models/hackathones/listNextHackathonesModel.js
server/src/routes/hackathonRoutes.js

endpoint que devuelve lista de hackathones a partir de la fecha de la solicitud

feat: listNextHackathones 

---

server/src/models/hackathones/listNextHackathonesModel.js

ahora devuelve tambien el numero de participantes

fix: listNextHackathones 

---

client/src/hooks/useHackathonesFromToday.js
client/src/pages/HomePage.jsx

ahora la landing renderiza los proximos eventos a partir de la fecha de hoy

feat: useHackathonesFromToday 

---

client/src/App.jsx
client/src/hooks/useBestHackathonesList.js
client/src/pages/ChangePassword.jsx

fix: ChangePassword 

---

server/src/routes/userRoutes.js

(pagina que envia codigo de recuperacion de contraseña si se te olvida)

feat: SendRecoverPassCode 

---

client/src/App.jsx
client/src/pages/SendRecoveryPassCode.jsx
client/src/pages/UseRecoveryPassCode.jsx
client/vite.config.js

(ahora desde el mail, accedemos al link para entrar en la pagina de nueva contraseña)

feat: UseRecoveryPassCode 

---

server/src/controllers/users/index.js
server/src/controllers/users/sendRecoveryPassEmailController.js
server/src/controllers/users/useRecoveryPassCodeController.js
server/src/models/users/updateUserPassRecoveryModel.js
server/src/routes/userRoutes.js

(no funcionaba el endpoint de recoveryPass, cambio la logica para extraer de query params el userId para su posterior uso, QUEDA FUNCIONANDO)

fix: recoveryPass

---

server/src/controllers/users/privateUserProfileController.js
server/src/models/users/showUserPrivateInfoModel.js

(ahora no enseña la contraseña en la informacion privada del usuario)

fix: showUserPrivateInfo 

---

client/src/App.jsx
client/src/pages/LoginPage.jsx
client/src/pages/UseRecoveryPassCode.jsx
server/src/controllers/users/sendRecoveryPassEmailController.js

(la consumicion de la api ahora es correcta, el mail redirecciona al componente correctamente)

fix: UseRecoverPassCode 

---

client/src/App.jsx
client/src/pages/ValidateUserPage.jsx
server/src/models/users/insertUserModel.js

(ahora funciona, ajuste en las rutas de backend y frontend, ajuste en el fetch del front)

fix: ValidateUserPage 

---

client/src/pages/PrivateUserProfilePage.jsx

(añadido boton para Cambiar Contraseña que redirecciona al componente [testeado])

fix: PrivateUserProfile 

---

client/src/App.jsx
client/src/components/Header.jsx
client/src/contexts/AuthContext.jsx
client/src/pages/PrivateUserProfilePage.jsx
client/src/pages/UpdateProfilePage.jsx
server/src/controllers/users/updateUserProfileController.js

Falta actualizar el avatar, el resto funciona correctamente

perfil privado y editar perfil
